title: prometheus-gs
tagline: A brand new course on Learning Lab
description: Hello world
template:
  repo: prometheus-gs-template
  name: prometheus-gs
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
